#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/allen/aibs/mat/ateam_shared/optimization_software/nrn-7.5"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/allen/aibs/mat/ateam_shared/optimization_software/nrn-7.5/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/home/joseph.nelson/DL4neurons/x86_64/.libs/libnrnmech.so" "$@"
